---
language: ruby
sudo: false
install: bundle install --without development
script: bundle exec rspec spec --color --format documentation
notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
    - rvm: 2.3.4
      env: TEST_VAGRANT_VERSION=v1.9.8
    - rvm: 2.4.4
      env: TEST_VAGRANT_VERSION=v2.0.4
    - rvm: 2.4.4
      env: TEST_VAGRANT_VERSION=v2.1.1
    - rvm: 2.4.4
      env: TEST_VAGRANT_VERSION=HEAD
